// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateUserInput struct {
	Name string  `json:"name"`
	ID   *string `json:"id,omitempty"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
